### ISSUE TITLE
Feature Request - goto "path/to/my/file:line:pos"

### ISSUE THREAD

**Issue by colin-kiegel** [atom/go-to-line#22]
The use case is *debugging errors* (like the one below) with a simple workflow
1. ctrl-g
2. path/to/my/file:123:4 (note: the format 'path/to/my/file:line:pos' seems to be very widespread)

-> Obviously this is not supported right now and throws an error.

It would be nice to support relative paths to the project root, or even autocomplete-matching such that 'to/my/file' would suggest all matching paths within the project, such as 'pathA/to/my/file' and 'pathB/to/my/file'.

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [go-to-line](https://github.com/atom/go-to-line) package, v0.30.0

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 89)

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:38

TypeError: Invalid Point: (NaN, 89)
  at Function.module.exports.Point.assertValid (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/point.js:65:15)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:956:13)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:1100:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/usr/share/atom/resources/app.asar/src/display-buffer.js:693:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/usr/share/atom/resources/app.asar/src/text-editor.js:2530:33)
  at GoToLineView.module.exports.GoToLineView.confirm (/usr/share/atom/resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:116:14)
  at atom-text-editor.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/go-to-line/lib/go-to-line-view.js:55:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -4:35.8.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -4:33.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:30.3.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -4:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:01.2.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -3:56.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:27.8.0 application:new-file (atom-text-editor.editor.is-focused)
     -3:26.1.0 core:close (atom-text-editor.editor.is-focused)
     -3:25.6.0 application:new-window (atom-text-editor.editor.is-focused)
     -0:14.6.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:13.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:11.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:09.2.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.38.0
keyboard-localization, v1.4.3
language-rust, v0.4.3
linter, v1.0.9
linter-rust, v0.1.0
minimap, v4.10.0
racer, v0.15.2

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Thanks for the report, @colin-kiegel -- I agree, that uncaught exception should be fixed. :+1:

However, I'm not convinced this package should provide the ability to jump to a specific `file:line:column` and also provide these features you asked about:

> It would be nice to support relative paths to the project root, or even autocomplete-matching such that 'to/my/file' would suggest all matching paths within the project, such as 'pathA/to/my/file' and 'pathB/to/my/file'.

Instead, I think [fuzzy finder](https://github.com/atom/fuzzy-finder) might be a better home for these. Fuzzy finder can already jump to a specific `file:line` (it can actually also jump to a specific line in the current file with just `:line`) and also show you fuzzy matches for a specific string (similar to autocomplete):

![screen shot 2015-07-02 at 19 48 13](https://cloud.githubusercontent.com/assets/38924/8483769/5529b4d6-20f3-11e5-81ce-1bb18c9b0457.png)

So, if I understood your suggestion correctly -- we could extend fuzzy finder so that it supports specifying a `column` as well (currently, it only supports `line`). How does that sound? :thought_balloon:

**Comment by colin-kiegel** [comment]
I think that sounds great and makes a lot of sense. I didn't know about fuzzy finder yet - thanks for the tip. :-)

**Comment by maxbrunsfeld** [comment]
> I think fuzzy finder might be a better home for these.

That's a good idea @izuzak. In fact, it seems like if we made fuzzy-finder support column navigation, we could possibly :fire: this entire package.

**Comment by izuzak** [comment]
Opened https://github.com/atom/fuzzy-finder/issues/115 to track the request above in fuzzy-finder. Thanks for fixing the uncaught exception, @maxbrunsfeld :metal:
