### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 44)

### ISSUE THREAD

**Issue by sbrl** [atom/go-to-line#37]
1. Copy something like `path/file.txt:56` to your clipboard
2. Press CTRL+G instead of CTRL+T by accident
3. Paste the contents of your clipboard into the box
4. Hit enter
5. Get exception :D

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Pro
**Thrown From**: [go-to-line](https://github.com/atom/go-to-line) package, v0.31.0

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 44)

```
At C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: (NaN, 44)
    at Function.module.exports.Point.assertValid (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1099:13)
    at MarkerLayer.module.exports.MarkerLayer.setMarkerRange (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:374:29)
    at Marker.module.exports.Marker.update (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\marker.js:338:20)
    at Marker.module.exports.Marker.setHeadPosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\marker.js:146:19)
    at DisplayMarker.module.exports.DisplayMarker.setHeadBufferPosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\text-buffer\lib\display-marker.js:146:32)
    at C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\cursor.js:82:31
    at Cursor.module.exports.Cursor.changePosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\cursor.js:668:7)
    at Cursor.module.exports.Cursor.setBufferPosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\cursor.js:80:19)
    at C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:1776:23
    at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:2050:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\text-editor.js:1775:19)
    at GoToLineView.module.exports.GoToLineView.confirm (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\go-to-line\lib\go-to-line-view.js:114:14)
    at atom-text-editor.<anonymous> (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\go-to-line\lib\go-to-line-view.js:55:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\me\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -6:26.8.0 core:save (atom-text-editor.editor.is-focused)
     -6:25.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -6:24.5.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -6:23.6.0 core:save (atom-text-editor.editor.is-focused)
     -5:59.3.0 project-find:show (atom-text-editor.editor.is-focused)
  2x -5:50.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:49.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.8.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:34.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:27.2.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.1.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:13.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 go-to-line:toggle (atom-text-editor.editor.is-focused)
     -0:02.6.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-gfm"
    ],
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-ternjs, v0.15.0 (active)
caniuse, v0.9.0 (active)
change-case, v0.6.3 (active)
color-picker, v2.2.2 (active)
column-select, v0.2.0 (active)
devdocs, v0.2.1 (active)
docblockr, v0.8.7 (active)
file-icons, v1.7.22 (active)
git-plus, v5.18.0 (active)
language-dots, v0.0.4 (active)
language-glsl, v2.0.1 (active)
language-markdown, v0.16.3 (active)
linter, v1.11.18 (active)
linter-jsonlint, v1.3.0 (active)
linter-php, v1.3.1 (active)
minimap, v4.25.0 (active)
minimap-codeglance, v0.4.5 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.6.0 (active)
minimap-selection, v4.4.0 (active)
minimap-titles, v1.8.1 (inactive)
move-status-items, v0.0.11 (active)
new-tab, v0.5.3 (active)
protector, v0.2.2 (active)
rainbow-tabs, v2.2.1 (active)
snippet-generator, v0.3.2 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by sbrl** [comment]
Thanks for fixing that one :smiley:
